# Generated by Django 5.0.6 on 2024-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_requestsjobtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestJobTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.JSONField(blank=True, null=True)),
                ('userID', models.CharField(blank=True, db_index=True, null=True)),
                ('JobID', models.CharField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestsJobTable',
        ),
    ]
