# Generated by Django 5.0.6 on 2024-07-10 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_requestjobtable_delete_requestsjobtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestjobtable',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
