# Generated by Django 5.0.6 on 2024-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_requestjobtable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstable',
            name='AcceptedIDs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
