# Generated by Django 5.0.6 on 2024-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_jobstable_acceptedids'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstable',
            name='AcceptedRequest',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
