# Generated by Django 5.0.6 on 2024-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_jobstable_acceptedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstable',
            name='CreatorsID',
            field=models.CharField(blank=True, null=True),
        ),
    ]
