# Generated by Django 5.0.6 on 2024-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_jobstable_creatorsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, null=True)),
                ('CareTacker', models.CharField(blank=True, db_index=True, null=True)),
                ('Location', models.CharField(blank=True, db_index=True, null=True)),
                ('Units', models.CharField(blank=True, null=True)),
                ('Tenants', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
